{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "e0d08494-5af0-4f5c-acff-69f5dcb4147b",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "incomplete input (2514686292.py, line 88)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  Cell \u001b[0;32mIn[1], line 88\u001b[0;36m\u001b[0m\n\u001b[0;31m    st.subheader(f\"📊 Evaluation Metrics: {model_choice\u001b[0m\n\u001b[0m                                                      ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m incomplete input\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.preprocessing import LabelEncoder, StandardScaler\n",
    "from sklearn.metrics import (\n",
    "    accuracy_score, precision_score, recall_score, \n",
    "    f1_score, roc_auc_score, matthews_corrcoef, \n",
    "    confusion_matrix, classification_report\n",
    ")\n",
    "\n",
    "# Page Setup\n",
    "st.set_page_config(page_title=\"BITS ML Assignment 2\", layout=\"wide\")\n",
    "\n",
    "st.title(\"📦 Product Success Classification Dashboard\")\n",
    "st.markdown(\"### M.Tech (DSE) - Machine Learning Assignment 2\")\n",
    "\n",
    "# --- SIDEBAR: DATA UPLOAD (Requirement a) ---\n",
    "st.sidebar.header(\"Step 1: Upload Data\")\n",
    "uploaded_file = st.sidebar.file_uploader(\"Upload Test CSV\", type=\"csv\") # [cite: 91]\n",
    "\n",
    "# --- SIDEBAR: MODEL SELECTION (Requirement b) ---\n",
    "st.sidebar.header(\"Step 2: Select Model\")\n",
    "model_choice = st.sidebar.selectbox( # [cite: 92]\n",
    "    \"Choose a Classification Model\",\n",
    "    (\"Logistic Regression\", \"Decision Tree\", \"kNN\", \"Naive Bayes\", \"Random Forest\", \"XGBoost\")\n",
    ")\n",
    "\n",
    "# Model Mapping to .pkl files\n",
    "model_map = {\n",
    "    \"Logistic Regression\": \"logistic.pkl\",\n",
    "    \"Decision Tree\": \"decision_tree.pkl\",\n",
    "    \"kNN\": \"knn.pkl\",\n",
    "    \"Naive Bayes\": \"naive_bayes.pkl\",\n",
    "    \"Random Forest\": \"random_forest.pkl\",\n",
    "    \"XGBoost\": \"xgboost.pkl\"\n",
    "}\n",
    "\n",
    "def preprocess_test_data(df):\n",
    "    \"\"\"Encodes categorical data and defines features[cite: 30].\"\"\"\n",
    "    data = df.copy()\n",
    "    \n",
    "    # Create target if not present for evaluation\n",
    "    if 'Target' not in data.columns and 'Success_Percentage' in data.columns:\n",
    "        data['Target'] = (data['Success_Percentage'] > 50).astype(int)\n",
    "    \n",
    "    # Label Encoding (Requirement 27-30)\n",
    "    le = LabelEncoder()\n",
    "    cat_cols = ['Category', 'Sub_category']\n",
    "    for col in cat_cols:\n",
    "        if col in data.columns:\n",
    "            data[col] = le.fit_transform(data[col].astype(str))\n",
    "            \n",
    "    # Features (Selecting the required 12+ features)\n",
    "    features = ['Price', 'Rating', 'No_rating', 'Discount', 'M_Spend', \n",
    "                'Supply_Chain_E', 'Sales_y', 'Sales_m', 'Market_T', \n",
    "                'Seasonality_T', 'Category', 'Sub_category']\n",
    "    \n",
    "    available_features = [f for f in features if f in data.columns]\n",
    "    return data[available_features], data['Target'] if 'Target' in data.columns else None\n",
    "\n",
    "# Main App Logic\n",
    "if uploaded_file is not None:\n",
    "    df_test = pd.read_csv(uploaded_file)\n",
    "    st.success(\"Dataset Uploaded!\")\n",
    "    \n",
    "    with st.expander(\"Preview CSV Data\"):\n",
    "        st.dataframe(df_test.head())\n",
    "\n",
    "    try:\n",
    "        # Load Model from /model folder [cite: 55]\n",
    "        model_path = f\"model/{model_map[model_choice]}\"\n",
    "        model = joblib.load(model_path)\n",
    "        \n",
    "        # Prepare Data\n",
    "        X_test, y_true = preprocess_test_data(df_test)\n",
    "        \n",
    "        # Scaling\n",
    "        scaler = StandardScaler()\n",
    "        X_test_scaled = scaler.fit_transform(X_test)\n",
    "        \n",
    "        # Run Prediction\n",
    "        y_pred = model.predict(X_test_scaled)\n",
    "        y_prob = model.predict_proba(X_test_scaled)[:, 1] if hasattr(model, \"predict_proba\") else y_pred\n",
    "        \n",
    "        # --- REQUIREMENT (c): METRICS DISPLAY ---\n",
    "        st.subheader(f\"📊 Model Performance: {model_choice}\")\n",
    "        if y_true is not None:\n",
    "            c1, c2, c3, c4, c5, c6 = st.columns(6) # [cite: 93]\n",
    "            c1.metric(\"Accuracy\", f\"{accuracy_score(y_true, y_pred):.3f}\")\n",
    "            c2.metric(\"AUC\", f\"{roc_auc_score(y_true, y_prob):.3f}\")\n",
    "            c3.metric(\"Precision\", f\"{precision_score(y_true, y_pred):.3f}\")\n",
    "            c4.metric(\"Recall\", f\"{recall_score(y_true, y_pred):.3f}\")\n",
    "            c5.metric(\"F1\", f\"{f1_score(y_true, y_pred):.3f}\")\n",
    "            c6.metric(\"MCC\", f\"{matthews_corrcoef(y_true, y_pred):.3f}\")\n",
    "            \n",
    "            # --- REQUIREMENT (d): CONFUSION MATRIX & REPORT ---\n",
    "            st.divider()\n",
    "            left, right = st.columns(2) # [cite: 94]\n",
    "            \n",
    "            with left:\n",
    "                st.subheader(\"Confusion Matrix\")\n",
    "                cm = confusion_matrix(y_true, y_pred)\n",
    "                fig, ax = plt.subplots()\n",
    "                sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax)\n",
    "                st.pyplot(fig)\n",
    "                \n",
    "            with right:\n",
    "                st.subheader(\"Classification Report\")\n",
    "                st.code(classification_report(y_true, y_pred))\n",
    "        else:\n",
    "            st.warning(\"Please ensure the CSV contains 'Success_Percentage' for metric calculation.\")\n",
    "            \n",
    "    except Exception as e:\n",
    "        st.error(f\"Error: {e}. Ensure models are saved in the 'model/' folder.\")\n",
    "else:\n",
    "    st.info(\"👋 Welcome! Please upload your test data CSV in the sidebar to begin.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
