{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "e0d08494-5af0-4f5c-acff-69f5dcb4147b",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "incomplete input (2514686292.py, line 88)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  Cell \u001b[0;32mIn[1], line 88\u001b[0;36m\u001b[0m\n\u001b[0;31m    st.subheader(f\"📊 Evaluation Metrics: {model_choice\u001b[0m\n\u001b[0m                                                      ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m incomplete input\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.preprocessing import LabelEncoder, StandardScaler\n",
    "from sklearn.metrics import (\n",
    "    accuracy_score, precision_score, recall_score, \n",
    "    f1_score, roc_auc_score, matthews_corrcoef, \n",
    "    confusion_matrix, classification_report\n",
    ")\n",
    "\n",
    "# Set Page Title and Layout\n",
    "st.set_page_config(page_title=\"BITS ML Assignment 2 - Classification\", layout=\"wide\")\n",
    "\n",
    "st.title(\"🚀 Product Success Classification App\")\n",
    "st.markdown(\"Developed for BITS Pilani M.Tech (DSE) Machine Learning Assignment 2.\")\n",
    "\n",
    "# --- SIDEBAR: DATA UPLOAD (Requirement 91) ---\n",
    "st.sidebar.header(\"1. Upload Test Data\")\n",
    "uploaded_file = st.sidebar.file_uploader(\"Upload test data (CSV format)\", type=\"csv\")\n",
    "\n",
    "# --- SIDEBAR: MODEL SELECTION (Requirement 92) ---\n",
    "st.sidebar.header(\"2. Choose Model\")\n",
    "model_choice = st.sidebar.selectbox(\n",
    "    \"Select ML Model for Prediction\",\n",
    "    (\"Logistic Regression\", \"Decision Tree\", \"kNN\", \"Naive Bayes\", \"Random Forest\", \"XGBoost\")\n",
    ")\n",
    "\n",
    "# Map UI names to saved filenames in /model folder\n",
    "model_map = {\n",
    "    \"Logistic Regression\": \"logistic.pkl\",\n",
    "    \"Decision Tree\": \"decision_tree.pkl\",\n",
    "    \"kNN\": \"knn.pkl\",\n",
    "    \"Naive Bayes\": \"naive_bayes.pkl\",\n",
    "    \"Random Forest\": \"random_forest.pkl\",\n",
    "    \"XGBoost\": \"xgboost.pkl\"\n",
    "}\n",
    "\n",
    "def preprocess_data(df):\n",
    "    \"\"\"Encodes categorical data and prepares features (Requirement 30).\"\"\"\n",
    "    data = df.copy()\n",
    "    \n",
    "    # Create target if not present (Success > 50%)\n",
    "    if 'Target' not in data.columns and 'Success_Percentage' in data.columns:\n",
    "        data['Target'] = (data['Success_Percentage'] > 50).astype(int)\n",
    "    \n",
    "    # Handle Categorical Columns (Label Encoding)\n",
    "    le = LabelEncoder()\n",
    "    cat_cols = ['Category', 'Sub_category']\n",
    "    for col in cat_cols:\n",
    "        if col in data.columns:\n",
    "            data[col] = le.fit_transform(data[col].astype(str))\n",
    "            \n",
    "    # Features required (Assignment demands Min 12 features)\n",
    "    features = ['Price', 'Rating', 'No_rating', 'Discount', 'M_Spend', \n",
    "                'Supply_Chain_E', 'Sales_y', 'Sales_m', 'Market_T', \n",
    "                'Seasonality_T', 'Category', 'Sub_category']\n",
    "    \n",
    "    # Check if all features exist in uploaded CSV\n",
    "    available_features = [f for f in features if f in data.columns]\n",
    "    \n",
    "    return data[available_features], data['Target'] if 'Target' in data.columns else None\n",
    "\n",
    "if uploaded_file is not None:\n",
    "    # Read Data\n",
    "    df_test = pd.read_csv(uploaded_file)\n",
    "    st.success(\"Test dataset loaded successfully!\")\n",
    "    \n",
    "    with st.expander(\"Preview Uploaded Dataset\"):\n",
    "        st.dataframe(df_test.head())\n",
    "\n",
    "    try:\n",
    "        # Load the selected model from the /model directory (Requirement 55)\n",
    "        model_path = f\"model/{model_map[model_choice]}\"\n",
    "        model = joblib.load(model_path)\n",
    "        \n",
    "        # Preprocess the uploaded CSV\n",
    "        X_test, y_true = preprocess_data(df_test)\n",
    "        \n",
    "        # Scale numerical values\n",
    "        scaler = StandardScaler()\n",
    "        X_test_scaled = scaler.fit_transform(X_test)\n",
    "        \n",
    "        # Predictions\n",
    "        y_pred = model.predict(X_test_scaled)\n",
    "        y_prob = model.predict_proba(X_test_scaled)[:, 1] if hasattr(model, \"predict_proba\") else y_pred\n",
    "        \n",
    "        # --- REQUIREMENT (c): DISPLAY EVALUATION METRICS (Requirement 93) ---\n",
    "        st.subheader(f\"📊 Evaluation Metrics: {model_choice}\")\n",
    "        m1, m2, m3, m4, m5, m6 = st.columns(6)\n",
    "        \n",
    "        if y_true is not None:\n",
    "            m1.metric(\"Accuracy\", f\"{accuracy_score(y_true, y_pred):.3f}\")\n",
    "            m2.metric(\"AUC Score\", f\"{roc_auc_score(y_true, y_prob):.3f}\")\n",
    "            m3.metric(\"Precision\", f\"{precision_score(y_true, y_pred):.3f}\")\n",
    "            m4.metric(\"Recall\", f\"{recall_score(y_true, y_pred):.3f}\")\n",
    "            m5.metric(\"F1 Score\", f\"{f1_score(y_true, y_pred):.3f}\")\n",
    "            m6.metric(\"MCC Score\", f\"{matthews_corrcoef(y_true, y_pred):.3f}\")\n",
    "            \n",
    "            # --- REQUIREMENT (d): CONFUSION MATRIX & REPORT (Requirement 94) ---\n",
    "            st.divider()\n",
    "            col_left, col_right = st.columns([1, 1])\n",
    "            \n",
    "            with col_left:\n",
    "                st.subheader(\"Confusion Matrix\")\n",
    "                cm = confusion_matrix(y_true, y_pred)\n",
    "                fig, ax = plt.subplots()\n",
    "                sns.heatmap(cm, annot=True, fmt='d', cmap='Greens', ax=ax)\n",
    "                ax.set_xlabel('Predicted Label')\n",
    "                ax.set_ylabel('True Label')\n",
    "                st.pyplot(fig)\n",
    "                \n",
    "            with col_right:\n",
    "                st.subheader(\"Classification Report\")\n",
    "                report = classification_report(y_true, y_pred)\n",
    "                st.code(report)\n",
    "        else:\n",
    "            st.warning(\"Target column (Success_Percentage) not found for evaluation metrics.\")\n",
    "            \n",
    "    except FileNotFoundError:\n",
    "        st.error(f\"Model file '{model_map[model_choice]}' not found. Ensure it is in the /model/ folder.\")\n",
    "    except Exception as e:\n",
    "        st.error(f\"Error processing data: {e}\")\n",
    "else:\n",
    "    st.info(\"💡 Please upload a CSV file in the sidebar to start evaluation.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
